apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
   replicas: 3
   selector: 
     app: myjavaapp
     version: 2.6.2
   template:
     metadata:
       labels:
          app: myjavaapp
          version: 2.6.2
     spec:
        containers:
        - name: myjavaapp-container   
          image: sipu1996/myjenkinsimage:1
          ports:
          - containerPort: 8080